export const descLookup = {
  "Scrap Metal": "Can be traded in at Fallout Bunker",
  "Nuclear Fuel Cell": "Maybe Ella can do something with this...",
  "Repair Kit": "Restores 30 HP",
  "Thick Carbon Coating": "Increases Max HP by 10",
  "Particle Battery": "Increases Base Damage by 2",
  "Plasma Grenade": "Deals 20 damage",
  "Portable Shield": "Generates a temporary shield",
  "Nuclear Heat Ray": "A very powerful weapon, it only has one shot...",
  "Smoke Bomb": "Covers area in smoke, making you harder to hit",
  "West Riddle Box": "There is something inscribed on the box...",
  "East Riddle Box": "There is something inscribed on the box...",
  "Office Keycard West": "Opens doors in R.U. West Tower",
  "Office Keycard East": "Opens doors in R.U. East Tower",
  "Office Keycard North": "Opens doors in R.U. North Tower",
  "North Tower Keycard": "Opens gate to R.U. North Tower",
  "Killswitch Code 1": "One of Three codes needed",
  "Killswitch Code 2": "One of Three codes needed",
  "Killswitch Code 3": "One of Three codes needed",
  "Missle Launcher": "Maybe Ella can do something with this...",
  "Combat Repair Module": "Maybe Ella can do something with this...",
  "Fission Cannon": "Maybe Ella can do something with this...",
  "Large Chest": "Open it up!...",
  EMP: "A targeted EMP charge, should disable most enemies",
  "Graphene Plating": "Increases Max HP by 30",
  "Regeneration Diode": "Maybe Ella can do something with this...",
  Letter: "Looks like James wrote it...",
  "Basement Keycard": "Opens doors in the Secret Basement",
};

export const getItemLookup = {
  pu_scrapmetal: "Scrap Metal",
  pu_particlebattery: "Particle Battery",
  pu_carboncoating: "Thick Carbon Coating",
  pu_repairkit: "Repair Kit",
  pu_grenade: "Plasma Grenade",
  pu_shield: "Portable Shield",
  pu_fuelcell: "Nuclear Fuel Cell",
  pu_heatray: "Nuclear Heat Ray",
  pu_bomb: "Smoke Bomb",
  pu_rbox: ["West Riddle Box", "East Riddle Box"],
  pu_launcher: "Missle Launcher",
  pu_module: "Combat Repair Module",
  pu_cannon: "Fission Cannon",
  pu_chest: "Large Chest",
  pu_emp: "EMP",
  pu_letter: "Letter",
  pu_plating: "Graphene Plating",
  pu_diode: "Regeneration Diode",
};

export const dropItemLookup = {
  drop_scrapmetal: "Scrap Metal",
  drop_particlebattery: "Particle Battery",
  drop_carboncoating: "Thick Carbon Coating",
  drop_repairkit: "Repair Kit",
  drop_grenade: "Plasma Grenade",
  drop_shield: "Portable Shield",
  drop_fuelcell: "Nuclear Fuel Cell",
  drop_heatray: "Nuclear Heat Ray",
  drop_bomb: "Smoke Bomb",
  drop_rbox: ["West Riddle Box", "East Riddle Box"],
  drop_launcher: "Missle Launcher",
  drop_module: "Combat Repair Module",
  drop_cannon: "Fission Cannon",
  drop_chest: "Large Chest",
  drop_emp: "EMP",
  drop_letter: "Letter",
  drop_plating: "Graphene Plating",
  drop_diode: "Regeneration Diode",
};

export const useableItemLookup = {
  use_repairkit: "Repair Kit",
  use_particlebattery: "Particle Battery",
  use_carboncoating: "Thick Carbon Coating",
  use_grenade: "Plasma Grenade",
  use_shield: "Portable Shield",
  use_bomb: "Smoke Bomb",
  use_heatray: "Nuclear Heat Ray",
  use_rbox: ["West Riddle Box", "East Riddle Box"],
  use_chest: "Large Chest",
  use_emp: "EMP",
  use_plating: "Graphene Plating",
};

export const intObjectLookup = {
  open_desk: "Desk",
  open_cabinet: "Filing Cabinet",
  open_fridge: "Refridgerator",
  open_safe: "Broken Safe",
};

export const directionMap = {
  dn: "north",
  ds: "south",
  de: "east",
  dw: "west",
};
